
project_id = "zllrplxlewqyipxxpetl"

[auth]
enabled = true
email_signup_enabled = true
email_confirmation_enabled = true
email_double_confirm_changes_enabled = false

[auth.email]
enabled = true

[auth.external.google]
enabled = false

[auth.external.github]
enabled = false

[functions.gumroad-checkout]
verify_jwt = false

[functions.gumroad-webhook]
verify_jwt = false

[functions.auto-scrape-jobs]
verify_jwt = false

[functions.scrape-jobs]
verify_jwt = true

[functions.optimize-resume]
verify_jwt = true

[functions.parse-ats-resume]
verify_jwt = true

[functions.score-resume]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.verify-subscription]
verify_jwt = true
