
project_id = "zllrplxlewqyipxxpetl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[[functions]]
name = "gumroad-checkout"
verify_jwt = true

[[functions]]
name = "gumroad-webhook"
verify_jwt = false

[[functions]]
name = "optimize-resume"
verify_jwt = true

[[functions]]
name = "score-resume"
verify_jwt = true

[[functions]]
name = "verify-subscription"
verify_jwt = true

[[functions]]
name = "sitemap"
verify_jwt = false
