
import React from 'react';

interface ATSFriendlyResumePdfTemplateProps {
  content: string;
  jobTitle?: string;
}

export const ATSFriendlyResumePdfTemplate = ({ content, jobTitle }: ATSFriendlyResumePdfTemplateProps) => {
  const currentDate = new Date();
  const formattedDate = currentDate.toLocaleDateString();
  
  // Try to extract sections from the resume content
  const lines = content.split('\n');
  
  // Simple function to determine if a line is likely a section header
  const isSectionHeader = (line: string): boolean => {
    const trimmed = line.trim();
    return (
      trimmed.length > 0 && 
      trimmed.length < 30 && 
      trimmed === trimmed.toUpperCase() ||
      /^(EXPERIENCE|EDUCATION|SKILLS|CERTIFICATIONS|SUMMARY|PROFILE|PROJECTS|ACHIEVEMENTS|REFERENCES)/i.test(trimmed)
    );
  };

  return (
    <div className="ats-resume-template p-8 bg-white text-black" style={{ fontFamily: 'Arial, sans-serif', lineHeight: '1.6' }}>
      <div className="pdf-header bg-slate-100 p-4 border-b border-slate-300 mb-6">
        <h1 className="text-2xl font-bold text-center text-slate-800">ATS-Optimized Resume</h1>
        {jobTitle && (
          <h2 className="text-xl text-center text-slate-700 mt-2">For: {jobTitle}</h2>
        )}
        <div className="text-sm text-center text-slate-600 mt-2">Generated on {formattedDate} by Resulient</div>
      </div>

      <div className="pdf-content">
        {lines.map((line, index) => {
          if (isSectionHeader(line)) {
            return (
              <h2 key={index} className="text-xl font-bold text-slate-800 mt-6 mb-3 border-b border-slate-300 pb-1">
                {line.trim()}
              </h2>
            );
          } else if (line.trim().length === 0) {
            return <div key={index} className="my-2"></div>;
          } else {
            return (
              <p key={index} className="my-1 text-slate-700">
                {line.trim()}
              </p>
            );
          }
        })}
      </div>
      
      <div className="pdf-footer mt-8 pt-4 border-t border-slate-300 text-center text-sm text-slate-500">
        <p>This resume has been optimized for Applicant Tracking Systems (ATS)</p>
        <p>Generated by Resulient - https://resulient.com</p>
      </div>
    </div>
  );
};
