// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zllrplxlewqyipxxpetl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbHJwbHhsZXdxeWlweHhwZXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDU3NzksImV4cCI6MjA2MDU4MTc3OX0.1TRnufxXW7jdyGLw260j3i_Wl4ciKhb_eMXc3G1uRtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);